### ISSUE TITLE
Is it required to have developer mode enabled on device?

### ISSUE THREAD

**Issue by kyrlon** [cradlepoint/sdk-samples#123]
It appears from this [link](https://docs.cradlepoint.com/r/NetCloud-Manager-Tools-Tab/Developer-Mode-Devices) that using any of the samples in this repository requires having the developer mode enabled. Is this verified? Right now, I receive timeouts when attempting to run any of the examples, or I get an error when using `requests` directly:
```
[SSL: CERTIFICATE_VERIFY_FAILED certificate verify failed : self signed certificate in certificate chain](https://stackoverflow.com/questions/76578915/ssl-certificate-verify-failed-certificate-verify-failed-self-signed-certifica)
```

**Comment by bmwagner18** [comment]
I used this guide to deploy an app without developer mode: https://customer.cradlepoint.com/s/article/NetCloudOS-SDK-Sample-Apps-Quick-Start-Guide
